name: LightBlocks
version: @project.version@
api-version: '1.21'
author: Jim (AnEnragedPigeon)
description: QoL features for Light block use
main: uk.co.notnull.lightblocks.LightBlocks

dependencies:
  server:
    WorldGuard:
      load: AFTER
      required: false
    GriefPrevention:
      load: AFTER
      required: false
