name: LightBlocks
version: @project.version@
api-version: '1.21.4'
author: Jim (AnEnragedPigeon)
description: QoL features for Light block use
main: uk.co.notnull.lightblocks.LightBlocks

dependencies:
  server:
    WorldGuard:
      load: AFTER
      required: false
    GriefPrevention:
      load: AFTER
      required: false

permissions:
  light.give:
    description: Allows players to give themselves a light block
    default: op
