name: LightBlocks
version: @project.version@
api-version: "1.20.6"
author: Jim (NotKatuen)
main: uk.co.notnull.lightblocks.LightBlocks
depend: [WorldGuard]
softdepend: [GriefPrevention]
commands:
  light:
    permission: light.give
    description: Gives you a light block of the specified level
    usage: /light <level 0-15>