[versions]
pluginYmlPaper = "0.9.0"
paperApi = "26.2.build.+"
griefPrevention = "18.0.0"
worldguard = "7.0.17"

[libraries]
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApi" }
griefPrevention = { group = "com.github.TechFortress", name = "GriefPrevention", version.ref  = "griefPrevention" }
worldguard =  { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version.ref  = "worldguard" }

[plugins]
pluginYmlPaper = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginYmlPaper" }